# Conclusion 

We developed two R packages - NonCompart and ncar for NCA. Through these packages, we aimed to imple ment the following functionalities for performing NCA: 1) CDISC SDTM terms; 2) automatic slope selection with the same criterion of WinNonlin®; 3) supporting both ‘linear-up linear-down’ and ‘linear-up log-down’ method; and 4) interval (partial) AUCs
with ‘linear’ or ‘log’ interpolation method. These packages
are convenient and efficient because they enable prepara-
tion of data and NCA as well as generation of reports includ-
ing plots together in R software. As shown in Figure 2B, the
NCA plot allows for automatic slope selection, however, it is not
possible to manually choose the points used for calculating ter-
minal slope. In addition, any error or change can easily be fixed,
and users may choose calculation methods between linear and
logarithmic, which support ‘linear-up linear-down’ and ‘linear-
up log-down’ method, respectively. Our results showed that our
R packages meet the aforementioned objectives.
Since the PPTESTCD of SDTM is used in the R packages, it
is helpful to construct PP domain. In the present practice, one
has to change variables from WinNonlin® one by one, which is
an especially difficult task for those without specific knowledge
on SDTM. A number of packages can perform NCA, but no
package-even commercial softwares-can give outputs in the
format of SDTM or receive SDTM-formatted input data. It is
important to ensure that the reports are legible to sponsors and
regulatory bodies by generating a consistent and systematic re-
sult, as well as the exact results of NCA.
As shown in Table 3, comparison of NCA results obtained
by WinNonlin® and ncar package (including another package)
showed no significant discrepancies. These two R packages are
fast and easy-to-use tool-set that can successfully perform NCA
with concentration–time data. Specifically, the ncar package can
produce a comprehensive set of graphical and tabular outputs
that summarize the NCA results, which is a complete report in
pdf or rtf format. Our two newly-developed packages are free
and open-source, so they can be used to develop other useful
packages as well. We hope that NonCompart and ncar packages
will enable researchers to easily perform NCA, and contribute
to facilitation of drug discovery process.
