---
title: "R packages for Noncompartmental Analysis"
author: "Sungpil Han"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
documentclass: krantz
bibliography: [bib/packages.bib, bib/manual.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
fontsize: 12pt
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
output:
  bookdown::gitbook:
    css: css/style.css
---

```{r setup, include = FALSE}
# library(tidyverse)
# library(NonCompart)
# library(ncar)
# library(knitr)
pkg <- c('tidyverse', 'NonCompart', 'ncar', 'knitr')
sapply(pkg, require, character.only = TRUE)
opts_chunk$set(message = FALSE, error = TRUE)
```

# Overview {-}

Noncompartmental analysis (NCA) is a primary analytical approach for pharmacokinetic studies, and its parameters act as decision criteria in bioequivalent studies. Currently, NCA is usually carried out by commercial softwares such as WinNonlin®. In this article, we introduce our newly-developed two R packages, NonCompart (NonCompartmental analysis for pharmacokinetic data) and ncar (NonCompartmental Analysis for pharmacokinetic Report), which can perform NCA and produce complete NCA reports in both pdf and rtf formats. These packages are compatible with CDISC (Clinical Data Interchange Standards Consortium) standard as well. We demonstrate how the results of WinNonlin® are reproduced and how NCA reports can be obtained. With these R packages, we aimed to help researchers carry out NCA and utilize the output for early stages of drug development process. These R packages are freely available for download from the CRAN repository.

# Acknowledgements {-}

This research was supported by the EDISON (EDucation-research Integration through Simulation On the Net) Program
through the National Research Foundation of Korea (NRF)
funded by the Ministry of Education, Science and Technology
(Grant number: 016M3C1A6936614). We thank Dr. Joon Seo
Lim from the Scientific Publications Team at Asan Medical
Center for his editorial assistance in preparing this manuscript.

\mainmatter

